import { Appointment, User } from './types';

export const dummyAppointments: Appointment[] = [
  {
    id: '1',
    testId: 'T-1001',
    name: 'أحمد محمود',
    phone: '0791234567',
    age: 35,
    location: 'عمان',
    testName: 'فحص دم شامل',
    date: '2024-05-15',
    time: '10:00',
    testerName: 'خالد عبد الله',
    price: 45.0,
    status: 'جديد',
  },
  {
    id: '2',
    testId: 'T-1002',
    name: 'سارة خالد',
    phone: '0787600000',
    age: 28,
    location: 'الزرقاء',
    testName: 'فحص فيتامين د',
    date: '2024-05-15',
    time: '11:30',
    testerName: 'منى علي',
    price: 30.0,
    status: 'قائم',
  },
  {
    id: '3',
    testId: 'T-1003',
    name: 'يوسف محمد',
    phone: '0771122334',
    age: 45,
    location: 'اربد',
    testName: 'فحص سكر تراكمي',
    date: '2024-05-14',
    time: '09:00',
    testerName: 'خالد عبد الله',
    price: 15.0,
    status: 'مكتمل',
    completionTime: '09:45',
    arrivalTime: '09:05',
  },
  {
    id: '4',
    testId: 'T-1004',
    name: 'ليلى حسن',
    phone: '0799887766',
    age: 52,
    location: 'عمان',
    testName: 'وظائف الكلى',
    date: '2024-05-14',
    time: '14:00',
    testerName: 'منى علي',
    price: 25.0,
    status: 'نتائج مستلمة',
    completionTime: '14:30',
    arrivalTime: '14:10',
  },
  {
    id: '5',
    testId: 'T-1005',
    name: 'عمر زيد',
    phone: '0785544332',
    age: 60,
    location: 'عمان',
    testName: 'مسحة كورونا',
    date: '2024-05-16',
    time: '12:00',
    testerName: '-',
    price: 20.0,
    status: 'ملغي',
  },
];

export const dummyUsers: User[] = [
  {
    id: 'U-001',
    name: 'محمد أحمد',
    email: 'admin@manzeli.com',
    role: 'مسؤول',
    status: 'نشط',
    phone: '0790000001',
    password: 'admin',
    governorate: 'كل المحافظات',
    shift: 'كلاهما'
  },
  {
    id: 'U-002',
    name: 'سالم محمود',
    email: 'scheduler@manzeli.com',
    role: 'مبرمج مواعيد',
    status: 'نشط',
    phone: '0790000002',
    password: 'password',
    governorate: 'كل المحافظات',
    shift: 'كلاهما'
  },
  {
    id: 'U-003',
    name: 'خالد عبد الله',
    email: 'khaled@manzeli.com',
    role: 'ساحب منزلي',
    status: 'نشط',
    phone: '0790000003',
    password: 'password',
    governorate: 'عمان',
    shift: 'كلاهما'
  },
  {
    id: 'U-004',
    name: 'منى علي',
    email: 'mona@manzeli.com',
    role: 'ساحب منزلي',
    status: 'غير نشط',
    phone: '0790000004',
    password: 'password',
    governorate: 'عمان',
    shift: 'صباحي'
  }
];
